# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '3.8'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=bitnami_myapp
  nginx:
    image: nginx:latest
    volumes:
      - ./src:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/ssl/key.pem:/root/ssl/key.pem
      - ./nginx/ssl/cert.pem:/root/ssl/cert.pem
    ports:
      - '8080:80'
      - '443:443'  
    depends_on:
      - mariadb
      - myapp
  myapp:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=bn_myapp
      - DB_DATABASE=bitnami_myapp
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mariadb